services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3232"
    depends_on:
      - postgresql
      - mongodb
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/project_tracker # Use service name 'postgresql'
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/project_tracker_log
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_MAIL_HOST: smtp.gmail.com
      SPRING_MAIL_PORT: 465
      SPRING_MAIL_USERNAME: ${gmail_account}
      SPRING_MAIL_PASSWORD: ${gmail_password}
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: true
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_PORT: 465
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_CLASS: javax.net.ssl.SSLSocketFactory
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SOCKETFACTORY_FALLBACK: false
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE: true

  postgresql:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: project_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.0-alpine
    ports:
      - "6380:6379"

volumes:
  postgresql_data:
  mongodb_data: