services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3232:3232"
    depends_on:
      - postgresql
      - mongodb
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/project_tracker # Use service name 'postgresql'
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: project_tracker_logs
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      # Add other Spring Boot specific environment variables if needed, e.g., for Actuator, Dotenv
      # SPRING_PROFILES_ACTIVE: docker # Example for activating a 'docker' profile
      # DOTENV_LOCATION: .env # If you use spring-dotenv with a specific file

  postgresql:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: project_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

volumes:
  postgresql_data:
  mongodb_data: